config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :recipes
  resources :foods
  resources :recipe_foods
  resources :users

   root "foods#index"
   get '/public_recipes', to: 'recipes#public_recipes'
  get '/general_shopping_list', to: 'foods#general_shopping_list'


end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = current_user.recipes
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @recipe_food = @recipe.recipe_foods.includes(:food)
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @recipe.user = current_user
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe_foods = RecipeFood.where(recipe_id: @recipe.id)
    @recipe_foods.each(&:destroy)

    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def public_recipes
    @public_recipes = Recipe.includes(:user, :recipe_foods).where(public: true)
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    redirect_to recipe_url(@recipe), notice: 'Set to public successfully'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end
end

app/views/recipes/_form.html.erb
<div class="form">
  <%= form_with(model: recipe) do |form| %>
    <% if recipe.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

        <ul>
          <% recipe.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form_content">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div class="form_content">
      <%= form.label :preparation_time, style: "display: block" %>
      <%= form.text_field :preparation_time %>
    </div>

    <div class="form_content">
      <%= form.label :cooking_time, style: "display: block" %>
      <%= form.text_field :cooking_time %>
    </div>

    <div class="form_content">
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description %>
    </div>

    <div>
      <%= form.label :public %>
      <%= form.check_box :public %>
    </div>

    <%= form.hidden_field :user_id, value: current_user.id%>

    <div class="submit_form">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/recipes/_public_recipe.html.erb
 
  
   <div class='public'>
    <div class="public_recipe-name-user">
     <h3 class='name-public'> Name<%= recipe.name %></h3>
     <h4 class='Byuser-public'>By User:<%= recipe.user.name%></h4>
   </div>
   <div class='public_recipe-total-price'>
     
       <h4> Total food Items: <%=recipe.recipe_foods.length%></h4>
      <%sum=recipe.recipe_foods.reduce(0) { |sum, recipe_food| sum + recipe_food.food.price.to_s.to_d*recipe_food.quantity.to_s.to_d }%>
      <h4>Total price:<%=sum%></h4>
      <%= link_to "See recipe", recipe%>
   </div>
   </div>

app/views/recipes/_public_toggle.html.erb
<%= form_for recipe, url: recipe_path(recipe), method: :patch do |f| %>
  <%= f.hidden_field :public, value: !recipe.public %>
  <%= f.submit recipe.public? ? 'Make Private' : 'Make Public' %>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" class='main-recipe-details'>
    <h1><%= recipe.name %></h1>
    <div class="recipe-show">
    <div class="recipe-details">
    <strong>Preparation time: <%= recipe.preparation_time %></strong>
    <% if can? :edit, recipe%>
  
    <%end%>
    <strong>Cooking time: <%= recipe.cooking_time %></strong>
      <strong>Description:</strong>
      <%= recipe.description %>
       </div>
       
        <%=render partial: 'recipes/public_toggle', locals: {recipe: recipe}%>
    </div>

   
</div>

app/views/recipes/edit.html.erb
<h1 class="title">Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<div class='recipe-container'>
  <div id="recipes">
  <%if @recipes.empty?%>
  <h2>No recipes</h2>
  <%else%>
      <% @recipes.each do |recipe| %>
      <div id=recipe>
        <div>
          <h2 class='name-recipe'><%= recipe.name %><span>     </span><%=recipe.id%></h2>
          <%= button_to "Remove", recipe, method: :delete %>
        </div>

        <div>
          <strong>Description:</strong>
          <%= recipe.description %>
            <button type="button" class="detail-btn btn"><%= link_to "Details", recipe %></button>
        </div>
      </div>
      
      
    <% end %>
    <% end %>
  </div>
  <button type="button" class="add-btn btn"><%= link_to "Add Recipe", new_recipe_path %></button>
</div>

app/views/recipes/new.html.erb
<div class="new_recipe">
     <h1>Add New recipe</h1>
     <%= render "form", recipe: @recipe %>
     <br>
     <div>
     <%= link_to "Back to recipes", recipes_path %>
     </div>

</div>

app/views/recipes/public_recipes.html.erb
<div class='public-main'>
<%if @public_recipes.empty?%>
  <h2>No Public recipes</h2>
  <%else%>
  <h1>Public Recipes</h1>
  
<%@public_recipes.each do |public_recipe|%>
<%=render partial: 'public_recipe', locals: {recipe: public_recipe}%>
<%end%>
<%end%>
</div>

app/views/recipes/show.html.erb
<div class=container>
  <p style="color: green"><%= notice %></p>
  <div class="recipe-detail">
    <%= render @recipe %>
  </div>
  <div class="act-btns">
    <button type="button" class="edit-btn btn"><%= link_to "Edit", edit_recipe_path(@recipe) %></button>
    <button type="button" class="back-btn btn"><%= link_to "Back", recipes_path %></button>
    <button type="button" class="gen-btn btn"> <%=link_to 'Generate shopping list', general_shopping_list_path%></button>
    <%=link_to 'Add ingredient', new_recipe_food_path(recipe_id: @recipe.id) if can? :edit, @recipe%>
  </div>
  <table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @recipe_food.includes([:food]).each do |recipe_food| %>
      <tr>
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %></td>
        <td>$ <%= recipe_food.quantity * recipe_food.food.price %></td>
        <td class="recipe-food-actions">
          <%= button_to 'Remove', recipe_food_path(recipe_food), class: "btn-delete", method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, recipe_food %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>



  <%= link_to "Back to recipes", recipes_path, class: "add-food-btn recipe-action" %>

  <%= button_to "Destroy this recipe", @recipe, class: "btn-delete", method: :delete if can? :destroy, @recipe %>
</div>