config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :recipes
  resources :foods
  resources :recipe_foods
  resources :users

   root "foods#index"
   get '/public_recipes', to: 'recipes#public_recipes'
  get '/general_shopping_list', to: 'foods#general_shopping_list'


end

app/views/shared/_alert.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_navbar.html.erb
<header>
  <h1 class="nav-title">Recipes App</h1>
  <nav class="navbar">
    <ul class="nav-list">
    <% if user_signed_in? %>
      <li class="nav-item"><%= link_to 'Foods', foods_path, class: "nav-link"%></li>
      <li class="nav-item"><%= link_to 'Public Recipes', public_recipes_path, class: "nav-link"%></li>
      <li class="nav-item"><%= link_to 'My Recipes', recipes_path, class: "nav-link"%></li>
      <li class="nav-item"><%= link_to 'Shopping List', general_shopping_list_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "Profile", edit_user_registration_path, class: "nav-link sign-out" %></li>
      <li class="nav-item"><%= link_to "Log out", custom_destroy_user_session_path, method: :delete, class: "nav-link sign-out" %></li>
    <% else %>
      <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
    <% end %>
    </div>
    </ul>
  </nav>
</header>