config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :recipes
  resources :foods
  resources :recipe_foods
  resources :users

   root "foods#index"
   get '/public_recipes', to: 'recipes#public_recipes'
  get '/general_shopping_list', to: 'foods#general_shopping_list'


end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods, dependent: :destroy
  belongs_to :user, optional: true

  validates :name, :measurement_unit, presence: true
  validates :price, :quantity, presence: true, numericality: { greater_than: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]
  before_action :find_user

  # GET /foods or /foods.json
  def index
    @foods = current_user.foods
  end

  # GET /foods/new
  def new
    @food = Food.new
    @food.user = current_user
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    @food.user = @user

    if @food.save
      redirect_to foods_url(current_user), notice: 'Food was successfully created.'
    else
      render :new, status: :unprocessable_entity

    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def find_user
    @user = current_user
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">


<tr>
<td><%= food.name %></td>
<td><%= food.measurement_unit %></td>
<td>$<%= food.price %></td>
<td>
<%= button_to 'Delete', food_path(food), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-delete' %>
</td>
</tr>
  <tr>
</div>

app/views/foods/_form.html.erb
<div class="form">
  <%= form_with(model: food) do |form| %>
    <% if food.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

        <ul>
          <% food.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

    <div>
      <%= form.label :quantity, style: "display: block" %>
      <%= form.number_field :quantity %>
    </div>
      
    <div class="add-btn-form btn"><%= form.submit %></div>
  <% end %>
</div>

app/views/foods/edit.html.erb
<div class="form">
  <h1>Editing food</h1>

  <%= render "form", food: @food %>

  <br>

  <div class="act-btns">
    <button type="button" class="show-btn btn"><%= link_to "Show Food", @food %></button>
    <button type="button" class="back-btn btn"><%= link_to "Back to foods", foods_path %></button>
  </div>
</div>

app/views/foods/general_shopping_list.html.erb
<section>
  <h1 class='title-shopping'>Shopping List</h1>
  <div class='container-amount-total'>
    <h2 class='amount-shopping'>Amount of items to buy: <%= RecipeFood.includes(:food).where(recipe_id: params[:id]).present? ? RecipeFood.includes(:food).where(recipe_id: params[:id]).length : 0 %></h2>
    <h2>Total value of food needed: <%= RecipeFood.includes(:food).where(recipe_id: params[:id]).present? ? RecipeFood.includes(:food).where(recipe_id: params[:id]).sum { |recipefood| (recipefood.quantity - recipefood.food.quantity) * recipefood.food.price } : 0 %></h2>
  </div>
  
<table class='table-shopping'>
<thead>
  <tr>
    <th>Food</th>
    <th>Quantity</th>
    <th>Price</th>
  </tr>
  </thead>
  <% if RecipeFood.includes(:food).where(recipe_id: params[:id]).present? %>
    <% RecipeFood.includes(:food).where(recipe_id: params[:id]).each do |foods| %>
      <tr class='table'>
      <tbody>
        <td><%= foods.food.name %></td>
        <td><%= foods.quantity - foods.food.quantity %></td>
        <td><%= foods.food.price * (foods.quantity - foods.food.quantity) %></td>
      </tr>
       <tbody>
    <% end %>
  <% end %>
</table>
</section>

app/views/foods/index.html.erb
<%=stylesheet_link_tag('food')%>
<section>
<button type="button" class='new-food'><%= link_to "New food", new_food_path  %></button>

<p style="color: green"><%= notice %></p>



<div id="foods">
 <table>
 <thead>
<tr>
<th>Food</th>
<th>Measurement Unit</th>
<th>Unit price</th>
<th>Actions</th>
</tr>
</thead>
<tbody>
  <% @foods.each do |food| %>
    <a href="/foods/<%=food.id%>"><%= render food %></a>
    
  <% end %>
   <tbody>
 </table>

</div>


<button type="button" class="back-button"><%= link_to "Back to User", current_user %></button>
</section>

app/views/foods/new.html.erb
<div class="container">
  <h1 class="title">New Food</h1>

  <%= render "form", food: @food %>

  <br>

  <div>
    
    <button type="button" class="back-btn btn"><%= link_to "Back to foods", foods_path %></button>
  </div>
</div>

app/views/foods/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @food %>

  <div>
    <button type="button" class="edit-btn btn"><%= link_to "Edit this food", edit_food_path(@food) %></button>


  <%= link_to "Back to foods", foods_path %>

 

</div>