config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :recipes
  resources :foods
  resources :recipe_foods
  resources :users

   root "foods#index"
   get '/public_recipes', to: 'recipes#public_recipes'
  get '/general_shopping_list', to: 'foods#general_shopping_list'


end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe

  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  load_and_authorize_resource
  before_action :set_recipe_food, only: %i[show edit update destroy]

  # GET /recipe_foods or /recipe_foods.json
  def index
    if can? :manage, @recipe
      @foods = @user.foods.all
      @recipe_foods = RecipeFood.all
    else
      @recipe_foods = []
      @foods = []
    end
  end

  # GET /recipe_foods/1 or /recipe_foods/1.json
  def show; end

  # GET /recipe_foods/new
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new
    @available_foods = Food.where(user: current_user)
  end

  # GET /recipe_foods/1/edit
  def edit; end

  # POST /recipe_foods or /recipe_foods.json
  def create
    @recipe_food = RecipeFood.new(recipe_food_params)

    @recipe = @recipe_food.recipe

    respond_to do |format|
      if @recipe_food.save
        format.html { redirect_to recipes_path(@recipe), notice: 'Recipe food was successfully created.' }

      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe_foods/1 or /recipe_foods/1.json
  def update
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(recipe_food_params)
      redirect_to recipe_path(@recipe_food.recipe), notice: 'Recipe Food was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /recipe_foods/1 or /recipe_foods/1.json
  def destroy
    @recipe = @recipe_food.recipe
    @recipe_food.destroy

    respond_to do |format|
      format.html { redirect_to recipe_url(@recipe), notice: 'Recipe food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id, :recipe_id)
  end
end

app/views/recipe_foods/_form.html.erb
<div class="form">
  <%= form_with(model: recipe_food) do |form| %>
    <% if recipe_food.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

        <ul>
          <% recipe_food.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
     <div class="field">
    <%= form.label :food_id %>
    <% if @available_foods.present? %>
     <%= form.collection_select(:food_id, @available_foods, :id, :name, {}, {}) %>
    <% else %>
      <p>No foods available. Please add food first.</p>
      <%= link_to "Add New Food", new_food_path %>
    <% end %>
  </div>

    <div class="field">
      <%= form.label :quantity, style: "display: block" %>
      <%= form.text_field :quantity %>
    </div>
   
     <div class="field">
    <%= form.label :recipe_id %>
    <%= form.collection_select(:recipe_id, [@recipe], :id, :name, disabled: true) %>
  </div>
 



    <div>
      <%= form.submit "Add", class: "btn" %>
    </div>
  <% end %>

</div>

app/views/recipe_foods/_recipe_food.html.erb
<div id="<%= dom_id recipe_food %>">
  <table>
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Actions</th>
      </tr> 
      <tr>
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.quantity %><%= recipe_food.food.measurement_unit %></td>
        <td><%="$"%><%= recipe_food.food.price.to_s.to_d*recipe_food.quantity.to_s.to_d %></td>
        <td class="f-act">
          <%if can? :destroy, recipe_food.recipe%>
          <button class="recipe_btn"><%= link_to "Modify", edit_recipe_food_path(id: recipe_food) %></button>
          <%= button_to "Remove", recipe_food, method: :delete %>
          <%end%>
        </td>
      </tr>
    </thead>
  </table>
</div>

app/views/recipe_foods/edit.html.erb
<div class="recipe-container">
<h1>EDITTING RECIPE FOOD</h1>

<%= render "form", recipe_food: @recipe_food %>
</div>
  <%#= link_to "Show this recipe food", @recipe_food %> 
  <%#= link_to "Back to recipe foods", recipe_foods_path %>

app/views/recipe_foods/index.html.erb
<h1>Recipe foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe food", new_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<div class="recipe-container">
<h1>NEW RECIPE FOOD</h1>

<%= render "form", recipe_food: @recipe_food %>
</div>

app/views/recipe_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe_food %>

<div>
  <%= link_to "Edit this recipe food", edit_recipe_food_path(@recipe_food) %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>

  <%= button_to "Destroy this recipe food", @recipe_food, method: :delete %>
</div>